POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "lol23333",
    "important": true
}

### 
GET http://localhost:3001/api/notes

###
PUT http://localhost:3001/api/notes/60f7ee9fff3cb629d872739a
Content-Type: application/json

{
    "content": "go is good",
    "important": "true"
}