POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "user id of the note ...",
    "important": true,
    "userId": "6109ec6a5c0d07042892e51d"
}

### 
GET http://localhost:3001/api/notes

###
PUT http://localhost:3001/api/notes/60f7ee9fff3cb629d872739a
Content-Type: application/json

{
    "content": "go is good",
    "important": "true"
}

### 
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "notes": [],
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

### 
GET http://localhost:3001/api/users